### ISSUE TITLE
No Translation Found

### ISSUE THREAD

**Issue by IoCalisto** [gitrous/origins#10]
Username: IoCalisto

When I try to submit my game key, the prompt returns "No Translation Found" I also discovered that any text input into the field and entered will return the same. I then opened the developer console to see if that could lead to further insight, and discovered that the game translator WAS denying keys (none that I've entered), and saw that my key was not listed. (Just double checked, it generates random keys when the "No Translation Found" prompt is displayed)

**Comment by gitrous** [comment]
Thank you for reporting, this will be investigated. Do not attempt to purchase any more Beta Keys in an attempt to fix the issue.

**Comment by gitrous** [comment]
The issue has been fixed.
