### ISSUE TITLE
Dying with door prompt

### ISSUE THREAD

**Issue by IoCalisto** [gitrous/origins#12]
IGN: IoCalisto

Died while interacting with a door, the "open door" prompt is now stuck. Even if I die or interact with the door again. This does not interfere with opening or closing doors, even the one affected, and I cannot interact with said door from range.

![RobloxScreenShot20190606_205850756](https://user-images.githubusercontent.com/29127255/59076983-5859c800-889e-11e9-8fcd-73195e4b2ac9.png)

Multiple doors can be affected at once, and there cane be multiple prompts overlapping

![RobloxScreenShot20190606_210642103](https://user-images.githubusercontent.com/29127255/59077208-285ef480-889f-11e9-837b-67a3bf660aed.png)

**Comment by gitrous** [comment]
Thank you for the report. The issue has been fixed.
