### ISSUE TITLE
more clothes

### ISSUE THREAD

**Issue by fsdfdsfsdasd** [gitrous/origins#26]
plez add more clothes

**Comment by gitrous** [comment]
This is very vague. Can you elaborate? Maybe some specific items of clothing?

**Comment by fsdfdsfsdasd** [comment]
basic clothing, people would wear, not a specific type any works, mostly casual clothing though

**Comment by gitrous** [comment]
Basic clothes that people would wear is still pretty vague. Any specific styles or links?

**Comment by fsdfdsfsdasd** [comment]
like basic color shirts, longsleeves, hoodies, jerseys, ect
