### ISSUE TITLE
Bugs i found 

### ISSUE THREAD

**Issue by kangaro1525** [gitrous/origins#42]
I found a few bugs that concern the delivery man job and the talking gui in the clothing shop 
![RobloxScreenShot20191113_214727088](https://user-images.githubusercontent.com/57730317/68804171-730c4600-0661-11ea-8275-13ad12189111.png)
and the video i can send via discord since github dose not support WMV files

**Comment by gitrous** [comment]
I don't handle translation issues, but if you tell me what language that is, I can contact the translator. And please, put each individual bug as a separate issue, and upload the video to YouTube.

**Comment by kangaro1525** [comment]
> I don't handle translation issues, but if you tell me what language that is, I can contact the translator. And please, put each individual bug as a separate issue, and upload the video to YouTube.

Well i speak Swedish but  i don't see this as a translation error Since even in English this doesn't translate into anything but gibberish.
