### ISSUE TITLE
Newspaper bug, (cant deliver specific rout after dying)

### ISSUE THREAD

**Issue by kangaro1525** [gitrous/origins#44]
https://youtu.be/Ysmy-ZtfYBM

**Comment by gitrous** [comment]
Please describe the issue, all the video shows is you opening a door to the showers, I don’t speak whatever language that is.

**Comment by gitrous** [comment]
Your issue title should be related to the bug so I know what kind of issue it is before opening it, I know it’s a bug on origins if it’s on the list

**Comment by kangaro1525** [comment]
oh sorry, The bug is that if i am supposed to deliver a news paper but die before so i then after reseting/dying cant deliver the newspaper

**Comment by gitrous** [comment]
Please edit the original post and title to say so
