### ISSUE TITLE
No 5.56x45mm sold in the gun store.

### ISSUE THREAD

**Issue by shaneblob06** [gitrous/origins#45]

**Comment by gitrous** [comment]
In American translations the 5.56 is called the .223 Remington.

**Comment by shaneblob06** [comment]
Not in the description of the M15

**Comment by gitrous** [comment]
Then it’s a translation error. I’ll address it, but be aware that translation errors are not part of the bug bounty program.

**Comment by shaneblob06** [comment]
Thank you, newer players everywhere will thank you
