### ISSUE TITLE
After leaving server it leaves a slot in player list.

### ISSUE THREAD

**Issue by kangaro1525** [gitrous/origins#48]
![RobloxScreenShot20191116_192140563 (2)](https://user-images.githubusercontent.com/57730317/68997424-92e07b80-08a6-11ea-974d-fb88d49fd775.png)
![RobloxScreenShot20191116_192140563](https://user-images.githubusercontent.com/57730317/68997426-98d65c80-08a6-11ea-8f7f-a05057050810.png)

**Comment by gitrous** [comment]
This is a known issue and is being investigated. Thank you for your report.
