### ISSUE TITLE
License Inspector Job deny button not working

### ISSUE THREAD

**Issue by shaneblob06** [gitrous/origins#49]
![robloxapp-20191116-1928036](https://user-images.githubusercontent.com/57776433/69001195-a260c400-08a8-11ea-988e-39e180410b47.gif)

**Comment by gitrous** [comment]
Please post your local error log

**Comment by shaneblob06** [comment]
Unfortunately, at the time you requested this, I am no longer in the same server. Sorry for the inconvenience

**Comment by gitrous** [comment]
If the bug occurs again, please show the screenshots, as we were unable to reproduce the issue.
