### ISSUE TITLE
Realstic notifications.

### ISSUE THREAD

**Issue by Enderpandi06** [gitrous/origins#7]
To make it realstic, there will be 4 stats.
Hunger.
Hydration.
Cold.
Hygiene.
However, make houses easy to buy and alot of apartments.
Hunger - You know this k
Hydration - Yeah, also this
Cold- This is to add an effect to game, that you can get sick if you don't stay in your house during night.
Hygiene - No one wants to stink, right? We have respect. You will need to shower every week.
And now, real thing;
You will remove the bars and make it like,
Hunger - You feel hungry. -  You think it will be good to eat.
Hydration - My mouth is on drought... - I should drink something.
Cold - Sigh, streets are cold... - Maybe I need a place to stay.
Hyigene - Man, I stink. - Should go get a shower ASAP.
That's easier than bars at least? :))

**Comment by Enderpandi06** [comment]
I mean, those are messages pop up when you are hungry ETC.

**Comment by gitrous** [comment]
Cold doesn't really make sense with the 24 hour time, some people will have to stay in their house all day because it'll always be night for them.
