### ISSUE TITLE
ltc and hdp temporary fix (dtc)

### ISSUE THREAD

**Issue by buckettttt** [gitrous/origins#70]
so as you know the app reading thing is broken completely, and a way to fix this is to open a discord channel for applying to ltcs and hdps. a fix for the whole tax thing would be that you need to give the reader whatever the tax is ingame. and if you thought "well thats DUMB" then you've thought correctly. the bloxell government does not need tax since it doesnt do anything. 

tl;dr
make discord apps for ltc and hdp
remove the tax system for now or make a bad one

**Comment by gitrous** [comment]
This is the Bloxell: Origins GitHub repository.
