### ISSUE TITLE
Make Money Printers For Noted Fans

### ISSUE THREAD

**Issue by xXPirateLordXx** [gitrous/origins#9]
This would be good for noted fans, and have something to gain for getting that rank. I suggest adding a certain amount gained for a duration, and have it overheat. If it overheats, have it explode. Also you could add it exploding if you shoot it enough.  This would help the game so there is a point of getting the Noted Fan role.

**Comment by gitrous** [comment]
I feel like money printers are unrealistic and overused in RP games, and if I were to add them limiting them to Noted Fans probably wouldn't be fair, as Noted Fans are just my friends or YouTubers/Developers.
